Аспекты!
frosty-dev/ss14-wwdp pull request #12
Opened 2024-08-10 12:46 UTC by Spatison

# Описание PR

Порт аспектов. Большую часть из них удалил, оставил только эти: 
- Traitored (Оповещение о предателях на станции)
- Skeleton (Превращение всех на станции в скелетов)
- Reflect (Отражение проджектайлов от стен)
- Present (Подарки!)
- Immersive (Сужение обзора видимости)
- Bombass ( Мины на станции)
- Nothing ( Пустой аспект)
## Медиа

## Тип PR

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: 
- add: Aspects!

2024-08-10 13:10 UTC, Aviu00 requested changes
Еще у звуков должны быть аттрибьюшены.

2024-08-10 13:10 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +            _timeElapsedForTators += frameTime;
Таймер не должен идти, если триторов нет на станции, то есть если роли еще не выданы.

2024-08-10 13:10 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +                var nig = tator.Mind.OwnedEntity;
var nig

2024-08-10 13:10 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +        private const float WackyAaa = 60;
Надо переименовать переменные, непонятно, что они означают.

2024-08-10 13:10 UTC, Aviu00 commented on Content.Shared/_White/WhiteCVars.cs
> +        CVarDef.Create("aspects.enabled", true, CVar.SERVERONLY);
Надо в конфиге `development.toml` отключить аспекты, чтобы на локалке они не доставали.

2024-08-10 13:10 UTC, Aviu00 commented on Content.Shared/_White/WhiteCVars.cs
> +        CVarDef.Create("aspects.chance", 0.33d, CVar.SERVERONLY);
Слишком большой шанс.

2024-08-10 13:10 UTC, Aviu00 commented on Resources/Prototypes/_White/Aspects/AspectsEntity.yml
> +  name: мина аспекта
Название должно быть как у обычной мины, но суффикс "аспект"

2024-08-10 13:10 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/PresentAspect.cs
> +            EntityManager.SpawnEntity("PresentRandomUnsafe", targetCoords);
Надо портироавть изменения в системе подарков, а также расставить компоненты `GiftIgnore` в прототипах.

2024-08-10 13:10 UTC, Aviu00 commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
> +  - type: ReflectAspectMark # WD EDIT
Надо еще на двери поставить компонент, и может на стёкла. Но если ставить на стёкла, то нужно убедиться, что лазеры не рефлектятся.

2024-08-10 15:16 UTC, DVOniksWyvern commented
Отвал жопы.

2024-08-10 16:54 UTC, PuroSlavKing commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
> +  - type: ReflectAspectMark # WD EDIT
> Надо еще на двери поставить компонент, и может на стёкла. Но если ставить на стёкла, то нужно убедиться, что лазеры не рефлектятся.

не помешает ли запуску сингулярности?

2024-08-10 17:12 UTC, Aviu00 commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
> +  - type: ReflectAspectMark # WD EDIT
Надо сделать, чтобы прожектайлы УЧ не рефлектились.

2024-08-10 17:50 UTC, ThereDrD0 commented
Портируй аспект на богатых предателей, который давай плюс 10 ТК. По мне было прикольно

2024-08-11 10:16 UTC, ThereDrD0 requested changes
Нужно добавить поддержку локализации для всех возможных строк + напиши, что портировал TelescopeSystem в название ПРа, описание и чейнжлог. В идеале это надо было вынести в отдельный ПР, следуя методике 1 фича - 1 пр

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +        private void AnnounceToTators(EntityUid uid, GameRuleComponent rule)
Всех татаров надо переименовать в трейторов

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +            {
Убрать лишние {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +        {
Убрать {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Base/AspectComponent.cs
> +        [DataField("name")]
Убрать из датафилдов строку названий, если она повторяет название переменной

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Base/AspectSystem.cs
> +            {
Убрать {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
> +            {
Убрать {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
> +                {
Убрать в 4ех проверках ниже {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
> +                {
убрать {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
> +                {
Убрать тут и в двух проверках ниже {}

2024-08-11 10:16 UTC, ThereDrD0 commented on Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
> +                {
Убрать {}

2024-08-11 12:54 UTC, ThereDrD0 commented
Вмержи мастер и пофикси все, после антаг рефактора там кое-что сбилось #10

2024-08-11 16:37 UTC, ThereDrD0 requested changes
Нужно подождать мержа телескоп системы, а так вроде нормально

2024-08-13 07:58 UTC, Aviu00 requested changes
Надо добавить `GiftIgnore` компонент всем прототипам, где он был в старой репе.

2024-08-13 07:58 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +            _time += frameTime;
Если роли триторов еще не выданы, то таймер не должен идти.

2024-08-13 07:58 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
> +            _time += frameTime;
Нужна проверка на наличие ентити с компонентом `TraitorRole` или что-то типо того.

2024-08-13 10:58 UTC, Aviu00 approved these changes

2024-08-14 18:47 UTC, Spatison commented on Content.Shared/_White/CVars.cs
> +public sealed class CVars
Ридер решил переименовать класс когда я переносил все в один файл

2024-08-15 03:25 UTC, Remuchi requested changes

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/Atmos/EntitySystems/HeatExchangerSystem.cs
>      }
какой WhiteCvars

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/Administration/Logs/AdminLogManager.cs
>      private TimeSpan _queueSendDelay;
Это явно не White Cvars

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/GameTicking/GameTicker.StatusShell.cs
> +        ///     For access to WhiteCVars in status responses.
Не WhiteCVars

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
> +    // I'm too lazy to make WhiteCVars.
Какие WhiteCVars

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
> +    // Everything below is overridden in the RampingStationEventSchedulerSystem based on WhiteCVars
Not WhiteCVars

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/BombassAspect.cs
> +public sealed class BombassAspect : AspectSystem<BombassAspectComponent>
Rename it to something normal

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/Components/BombassAspectComponent.cs
> +public sealed partial class BombassAspectComponent : Component
Rename it to something normal

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/NothingAspect.cs
> +public sealed class NothingAspect : AspectSystem<NothingAspectComponent>
Зачем нам аспект Ничего?

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/_White/Other/GiftIgnoreComponent.cs
> +public sealed partial class GiftIgnoreComponent : Component
Не лучше ли это вынести в отдельный тэг, вместо создавания целого компонента без логики?

2024-08-15 03:25 UTC, Remuchi commented on Content.Server/_White/Other/ReflectAspectMarkComponent.cs
> +}
Тоже было бы неплохо это тегом сделать.

2024-08-15 03:25 UTC, Remuchi commented on Content.Shared/CCVar/CCVars.cs
> +        /// Whether to load the preset development WhiteCVars.
Not WhiteCVars

2024-08-15 03:25 UTC, Remuchi commented on Content.Shared/CCVar/CCVars.cs
> +        /// Whether to load the preset debug WhiteCVars.
Not WhiteCVars

2024-08-15 03:25 UTC, Remuchi commented on Content.Shared/_White/WhiteCVars.cs
> +    #region Aspects
Зачем ты файл то переименовал весь? Файл должен оставаться `CVars.cs`, а не `WhiteCVars.cs`

2024-08-15 03:25 UTC, Remuchi commented on Resources/ConfigPresets/Build/development.toml
> +enabled = false
Это не тут должно быть выключено, а в WhiteCVars. Аспекты по-умолчанию должны быть выключены везде, и включаться отдельно на хосте

2024-08-15 03:25 UTC, Remuchi commented on Resources/Locale/en-US/_white/aspects/aspects.ftl
> +aspect-traitored-announce-name = { $name } - FUCKING KILL HIM
убери излишнее "FUCKING KILL HIM" и замени на что-то более адекватное

2024-08-15 03:25 UTC, Remuchi commented on Resources/Locale/ru-RU/_white/aspects/aspects.ftl
> +aspect-traitored-announce-name = { $name } - УБЕЙ ЕГО НАХУЙ!
излишние маты не нужны в коде

2024-08-15 03:25 UTC, Remuchi commented on Resources/Prototypes/_White/Aspects/Aspects.yml
> +  id: BombassAspect
нейминг

2024-08-15 06:27 UTC, Aviu00 commented on Content.Shared/_White/WhiteCVars.cs
> +    #region Aspects
Иначе придется писать каждый раз Content.Shared._White.CVars, ибо нейминг конфликтует с движковыми кварами

2024-08-15 06:27 UTC, Aviu00 commented on Content.Server/_White/Other/GiftIgnoreComponent.cs
> +public sealed partial class GiftIgnoreComponent : Component
Компонентом удобнее в коде и в прототипах

2024-08-15 06:28 UTC, Aviu00 commented on Content.Server/_White/Other/ReflectAspectMarkComponent.cs
> +}
Компонентом удобнее, можно сделать query

2024-08-15 06:28 UTC, Aviu00 commented on Content.Server/_White/AspectsSystem/Aspects/NothingAspect.cs
> +public sealed class NothingAspect : AspectSystem<NothingAspectComponent>
Форсить при ивентах, чтобы не было других аспектов, а так он не должен сам срабатывать

2024-08-15 06:29 UTC, Aviu00 commented on Content.Shared/_White/WhiteCVars.cs
> +    #region Aspects
А, ты про сам файл. Тогда да

2024-08-15 12:14 UTC, ThereDrD0 approved these changes

2024-08-15 13:20 UTC, Spatison commented on Content.Server/_White/AspectsSystem/Aspects/PresentAspect.cs
> +            EntityManager.SpawnEntity("PresentRandomUnsafe", targetCoords);
SpawnEntity тут больше подходит.

2024-08-17 03:10 UTC, merged