[Port] TTS System
frosty-dev/ss14-wwdp pull request #20
Opened 2024-08-12 10:05 UTC by Remuchi

# Описание PR

Вся та же система TTS, что и раньше. Удалены из общего доступа голоса некоарк. Все остальное не менялось, за исключением мелких правок.

## Тип PR

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: 
- add: Система TTS

2024-08-12 10:50 UTC, Aviu00 requested changes

2024-08-12 10:50 UTC, Aviu00 commented on Content.Client/_White/TTS/HumanoidProfileEditor.TTS.cs
> +        _ttsManager.RequestTTS(dummny.Value, IoCManager.Resolve<IRobustRandom>().Pick(_sampleText), Profile.Voice);
Не надо резолвить каждый раз рандом.

2024-08-12 10:50 UTC, Aviu00 commented on Content.Client/_White/TTS/HumanoidProfileEditor.TTS.cs
> +        var dummny = _controller.GetPreviewDummy();
dummy а не dummny

2024-08-12 10:50 UTC, Aviu00 commented on Content.Server.Database/Migrations/Postgres/20240812081535_TtsVoices.cs
> +        }
А чего оно пустое.

2024-08-12 11:43 UTC, Remuchi commented on Content.Server.Database/Migrations/Postgres/20240812081535_TtsVoices.cs
> +        }
Без идей. Это было через автогенерацию сделано. Видимо она так решила.

2024-08-14 14:25 UTC, Aviu00 approved these changes

2024-08-14 14:27 UTC, merged