feat: port AnimatedLobby
frosty-dev/ss14-wwdp pull request #27
Opened 2024-08-14 16:11 UTC by trest100

# Описание PR
Ported AnimatedLobby

## Медиа

## Тип PR

- [ ] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: trest100

- tweak: Портированы анимированные фоны вместе с их системой

2024-08-14 19:09 UTC, Remuchi commented
Проставь лицензии у изображений как минимум.

2024-08-15 02:51 UTC, Remuchi requested changes
Так же тесты провалились. Посмотри причину и исправь. Проблема как раз в лобби.

2024-08-15 02:51 UTC, Remuchi commented on Content.Client/_Ohio/UI/AnimatedBackgroundControl.cs
> +
Никаких неймспейсов OHIO. Все это должно быть под неймспейсом WhiteDream

2024-08-15 02:59 UTC, Remuchi commented on Resources/Textures/White/Lobby/backgrounds/3.rsi/meta.json
> +  "copyright": WhiteDream,
Все названия тут должны быть внутри "". Из-за этого и ломается билд и тесты. 
"CC-BY-NC-SA-4.0",
"White Dream"

2024-08-15 12:02 UTC, trest100 commented on Resources/Textures/White/Lobby/backgrounds/3.rsi/meta.json
> +  "copyright": WhiteDream,
fixed

2024-08-15 12:02 UTC, trest100 commented on Content.Client/_Ohio/UI/AnimatedBackgroundControl.cs
> +
ok

2024-08-15 15:25 UTC, Remuchi commented
Ошибки линтера не связаны с пулл реквестом

2024-08-15 15:27 UTC, Remuchi approved these changes

2024-08-15 15:27 UTC, merged