ПНВ, порт+рефактор
frosty-dev/ss14-wwdp pull request #29
Opened 2024-08-16 06:53 UTC by RedFoxIV

# Описание PR
ПНВ с основного билда. Зарефакторен с учётом того, что им будут пользоваться люди, а не животные.
Плюсом фича, что вспышки бьют больнее, если пнв надет и включён.

Вторым плюсом кастумизируемость оверлеев (если они наследуются от GlassesOverlay)
![image](https://github.com/user-attachments/assets/09f2bce0-19e9-442f-a4ff-f1d84998e5bd)

Все фичи, предназначенные для пользования мапперами/другими кодерами подписаны в коде и объяснены

## Тип PR
- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [x] Refactor
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: 
- add: Прибор ночного видения.

2024-08-16 07:50 UTC, Remuchi commented
Проблемы с RSI не относятся к пулл реквесту

2024-08-16 11:56 UTC, ThereDrD0 requested changes

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +public abstract class BaseEnhancedVisionSystem<TComp, TToggleEvent> : BaseSharedEnhancedVisionSystem<TComp, TToggleEvent>
Если это не надо - убери

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Overlays/ClothingOverlay.cs
> +            return (bool) val;
Убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Overlays/ClothingOverlay.cs
> +            return (int) val;
Убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Nightvision/NightVisionSystem.cs
> +
Убери кучу новых строк, между всем по одной новой строчке должно быть

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +            _overlay.AddOverlay((Overlay) comp.Overlay);
убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +            _overlay.RemoveOverlay((Overlay) comp.Overlay);
Убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Shared/_White/Nightvision/NightVisionComponent.cs
> +    [DataField("requiredSlot")]
Убери текстовый датафилд, он повторяет строчку

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Shared/_White/Nightvision/SharedNightVisionSystem.cs
> +                EnableNV(uid, comp);
Убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Shared/_White/Nightvision/SharedNightVisionSystem.cs
> +                DisableNV(uid, comp);
Убери {}

2024-08-16 11:56 UTC, ThereDrD0 commented on Content.Shared/_White/Overlays/SharedClothingOverlaySystem.cs
> +    //public void OnToggle(EntityUid uid, ClothingOverlayComponent comp, ClothingOverlayToggleEvent args)
Закомментируй через /**/

2024-08-16 12:28 UTC, Remuchi requested changes

2024-08-16 12:28 UTC, Remuchi commented on Content.Client/_White/Nightvision/NightVisionSystem.cs
> +        if (!_timing.IsFirstTimePredicted) // why the fuck does it trigger, like, 10 times every time i equip it???
комментарии по стерильнее пожалуйста

2024-08-16 12:28 UTC, Remuchi commented on Content.Client/_White/Overlays/ClothingOverlay.cs
> +using Robust.Shared.Sandboxing; // fucking
не надо сандбокс ебать пожалуйста

2024-08-16 12:28 UTC, Remuchi commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +    [Dependency] private readonly IReflectionManager _wehavereflectionathome = default!;
нормальное название дял зависимости пожалуйста

2024-08-16 12:28 UTC, Remuchi commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +            Log.Error($"An empty overlay was specified in {protoid} prototype, or ClothingOverlayComponent was added in VV. If it's the former, either specify an overlay or remove the component. If i
Было бы неплохо добавить возможность добавлять этот компонент через VV и указывать там нужный тип шейдеров вручную.

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/Flash/Components/FlashVulnerabilityComponent.cs
> +}
Это должно быть в папке Вайта

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/Flash/FlashSystem.cs
> +            flashable.Duration = finalDuration;
если ты меняешь код оффициалов, подписывай это // White Dream в комментарии

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/Flash/FlashSystem.cs
> +            SubscribeLocalEvent<FlashVulnerabilityComponent, FlashAttemptEvent>(OnFlashVulnerableFlashAttempt);
// White Dream

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/Flash/FlashSystem.cs
> +        }
// White Dream

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/Flash/FlashSystem.cs
> +        public float DurationOffset = 1f;
// White Dream start
// White Dream end

2024-08-16 12:28 UTC, Remuchi commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  description: Продаётся в вашем ближайшем лыжном магазине второго уровня.
Изначально название и описание должны быть на английском. Перевод выполняется в файлах локалей

2024-08-16 12:28 UTC, Remuchi commented on Resources/Textures/Clothing/Eyes/Glasses/nightvision.rsi/equipped-EYES-off.png
эти файлы и шейдер должны быть в папках Вайта

2024-08-16 12:28 UTC, Remuchi commented on Resources/Prototypes/Actions/types.yml
все прототипы, экшены и прототипы шейдеров должны быть в папках вайта

2024-08-16 12:28 UTC, Remuchi commented on Resources/Audio/Items/nvg_activate.ogg
все звуки должны быть в папках Вайта

2024-08-16 12:28 UTC, Remuchi commented on Content.Server/_White/NightVision/NightVisionSystem.cs
> +        }
А каким образом накидывается компонент `FlashVulnerability`?

2024-08-16 12:28 UTC, Remuchi commented on Content.Shared/_White/Overlays/SharedClothingOverlaySystem.cs
> +        //SubscribeLocalEvent<ClothingOverlayComponent, ClothingOverlayToggleEvent>(OnToggle);
Если это не нужно, то сноси

2024-08-16 12:28 UTC, Remuchi commented on Content.Shared/_White/Overlays/SharedClothingOverlaySystem.cs
> +
в приватных методах в начале названия не ставится `_`

2024-08-16 12:50 UTC, RedFoxIV commented
сорок лет как под наркозом

2024-08-16 12:52 UTC, RedFoxIV commented on Content.Client/_White/Overlays/ClothingOverlay.cs
> +            return (bool) val;
однострочные ифы - рассадник непонятных багов, ради сокращения кода на две строки. попрошу ещё раз это обдумать, но если пиздец как требуемо - то уберу

2024-08-16 12:54 UTC, RedFoxIV commented on Content.Shared/_White/Nightvision/NightVisionComponent.cs
> +    [DataField("requiredSlot")]
переменная начинается с заглавной, а датафилд его подписывает со строчной
неиронично большая разница, в в прототипах всё держится со строчных

2024-08-16 12:54 UTC, RedFoxIV commented on Content.Client/_White/Nightvision/NightVisionSystem.cs
> +        if (!_timing.IsFirstTimePredicted) // why the fuck does it trigger, like, 10 times every time i equip it???
my honest reaction

2024-08-16 12:56 UTC, RedFoxIV commented on Content.Client/_White/Overlays/ClothingOverlaySystem.cs
> +            Log.Error($"An empty overlay was specified in {protoid} prototype, or ClothingOverlayComponent was added in VV. If it's the former, either specify an overlay or remove the component. If i
покажи, какой ивент вызывается при изменении переменной через VV и я попробую тебе закостылить позднюю инициализацию

2024-08-16 12:57 UTC, RedFoxIV commented on Content.Server/_White/NightVision/NightVisionSystem.cs
> +        }
в прототипе
не хочешь повышенную восприимчивость от пнв - вырезаешь с прототипа

2024-08-16 12:57 UTC, RedFoxIV commented
я работал кодербасом

2024-08-16 16:32 UTC, ThereDrD0 commented on Content.Shared/_White/Nightvision/NightVisionComponent.cs
> +    [DataField("requiredSlot")]
Прототип сам букву берет строчную вместо первой заглавной, все продумано

2024-08-16 16:40 UTC, RedFoxIV commented on Content.Shared/_White/Nightvision/NightVisionComponent.cs
> +    [DataField("requiredSlot")]
починил везде, где это было

2024-08-16 23:17 UTC, ThereDrD0 approved these changes
Как только ремучи нажмет апрув можно мержить

2024-08-17 03:14 UTC, Remuchi commented on Content.Server/Flash/Components/FlashVulnerabilityComponent.cs
> +}
Все еще не резольвнуто

2024-08-17 03:15 UTC, Remuchi commented on Content.Server/Flash/Components/FlashVulnerabilityComponent.cs
Все еще не исправлено. Должно быть в папке Вайта.

2024-08-17 03:16 UTC, Remuchi commented
Замечания о файлах ресурсах в папках Вайта все еще не исправлены

2024-08-18 16:59 UTC, RedFoxIV commented
PR's closed due to AIDS

2024-08-18 16:59 UTC, closed without merging