Cortical Borer
frosty-dev/ss14-wwdp pull request #7
Opened 2024-08-09 21:07 UTC by kurokoTurbo

# Description
Minor antag. Borers spawn randomly via station event.
Their objective is to infect a host and reproduce inside the host. Borers can inject various chemicals into host's bloodstream and even temporarily take control of host's body. To prevent infection or to get rid of the ascaridia - eat sugar.
---

# Changelog

:cl: Martell, MJ Sailor
- add: Cortical borers have appeared on the station

2024-08-09 21:13 UTC, kurokoTurbo commented
also this will need rework once new med system will be merged

2024-08-10 01:27 UTC, PuroSlavKing commented on Resources/Prototypes/_White/Borer/borer.yml
> +  id: ActionInfest
Убери отсюда Actions, они должны быть по пути Prototypes/_White/Actions

2024-08-10 01:27 UTC, PuroSlavKing commented on Resources/Prototypes/_White/Borer/borer.yml
> +  id: MobSimpleBorer
Должен быть просто MobBorer, у него нету Extended, или Ultimate версии.
Так же прототип смотрится лучше, когда он составляется вот так, то есть схож с большинством:
- parent
- id
- noSpawn/abstract...
- name
- description

2024-08-10 03:11 UTC, Remuchi requested changes
Не буду докапываться до деталей, исправь все ТУДУшки, почини пожалуйста кодстайл - много лишних пустых строк - и добавь аскаридам связь друг с другом, по принципу как у Лингов.
Еще в текущей вариации на актуальном репозитории Вайта при захвате разума пропадает UI химикатов, проверь это здесь пожалуйста.

2024-08-10 03:11 UTC, Remuchi commented on Content.Shared/_White/Borer/SharedBorerSystem.cs
> +        _action.AddAction(uid, ref component.ActionBorerOutEntity, component.ActionBorerOut, component: comp);
еще одна туду которую можно исправить

2024-08-10 05:35 UTC, idoffront commented
делайте я уже готов пиздить

2024-08-10 05:54 UTC, kurokoTurbo commented on Resources/Prototypes/_White/Borer/borer.yml
> +  id: ActionInfest
таки зачем? все у борера в одном месте, по-моему прекрасно

2024-08-10 06:40 UTC, kurokoTurbo commented
в целом вердикт по этой системе - все захардкодено, мне пока лень все в прототипы перенести, а еще мне этот антаг не нравится. 
весь функционал InfestedBorerComponent надо перенести в BorerComponent, откуда уже можно все значения в прототипы перенести.
также не вижу смысла разделения на BorerHostSystem и ServerBorerSystem

2024-08-10 06:52 UTC, PuroSlavKing commented on Resources/Prototypes/_White/Borer/borer.yml
> +  id: ActionInfest
Потому-что все возможные типы и виды прототипов в одном файле это колхоз, ты же не пишешь компонент и систему в одном файле

2024-08-11 12:53 UTC, ThereDrD0 commented
Вмержи мастер и почини борера для антаг рефактора #10, если это требуется. И рефакторни его под новый кодстайл, если сможешь.

2024-08-18 20:09 UTC, kurokoTurbo commented
closing while drama is in progress

2024-08-18 20:09 UTC, closed without merging